version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - ls -l ./
      #- terraform apply -var-file="dev-app.tfvars" -var="createdBy=e2esa" --auto-approve
      #- terraform apply --auto-approve --var-file=.dev-app.tfvars
      - terraform apply --auto-approve

