version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - ls -l ./
      #- ls -l ./dev-app.tfvars
      - terraform apply -auto-approve -var-file="./variables/dev-app.tfvars"
      #- terraform apply --auto-approve --var-file=./dev-app.tfvars 
