version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
      - terraform plan -var-file="./dev-app.tfvars"
  
  build:
    commands:
      - ls -l ./
      - ls -l ./dev-app.tfvars
      - terraform apply -var-file="./dev-app.tfvars" -var="createdBy=AFBN" -auto-approve
      #- terraform apply --auto-approve --var-file=./dev-app.tfvars
