version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform apply -var-file="./buildspec/dev-app.tfvars" -var="createdBy=AFBN" --auto-approve